site_name: ZCR

theme:
  name: material
  language: ko
  # logo: 
  # favicon: 
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate  
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  
  features:
    # Navigation settings
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    # search settings
    - search.suggest
    - search.highlight

# extra:
#   analysis:
#     provider: google
#     property: 'G-XXXXXXXXXX'
#   giscus:
  
# plugins
plugins:
  - search:
      lang: ko
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
  - git-revision-date-localized:
      type: iso_datetime
  - awesome-pages
